# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tURru4P0PoYMIBRh0Ub20l6m3nOQn8nM
"""

n=7
print (n*n)